ci: limiting mirroring concurrency
## Problem
Mirroring actions are failing because other actions have already mirrored what
it was about to mirror.

E.g.

* https://github.com/DeveloperC286/starlingbanktechnicalchallenge/actions/runs/7639729071/job/20813352947

```
Run git push --mirror "***gitlab.com/DeveloperC/${REPOSITORY_NAME}"
warning: redirecting to https://gitlab.com/DeveloperC/starlingbanktechnicalchallenge.git/
remote: error: cannot lock ref 'refs/heads/earthly_upgrade': unable to resolve reference 'refs/heads/earthly_upgrade'
remote: error: cannot lock ref 'refs/pull/92/head': reference already exists
To https://gitlab.com/DeveloperC/starlingbanktechnicalchallenge
   f4c0fa2..dfc1c32  main -> main
 ! [remote rejected] earthly_upgrade (failed to update ref)
 ! [remote rejected] refs/pull/92/head -> refs/pull/92/head (failed to update ref)
error: failed to push some refs to 'https://gitlab.com/DeveloperC/starlingbanktechnicalchallenge'
```

* https://github.com/DeveloperC286/starlingbanktechnicalchallenge/actions/runs/7639728988/job/20813352607

```
Run git push --mirror "***gitlab.com/DeveloperC/${REPOSITORY_NAME}"
warning: redirecting to https://gitlab.com/DeveloperC/starlingbanktechnicalchallenge.git/
remote: error: cannot lock ref 'refs/heads/main': is at dfc1c32915b02d9cb35ab831580cb9216eaf06bd but expected f4c0fa268dbaba173d11160b562dd823c5427d3b
To https://gitlab.com/DeveloperC/starlingbanktechnicalchallenge
 - [deleted]         earthly_upgrade
 * [new reference]   refs/pull/92/head -> refs/pull/92/head
 ! [remote rejected] main -> main (failed to update ref)
error: failed to push some refs to 'https://gitlab.com/DeveloperC/starlingbanktechnicalchallenge'
```

## Solution
So we are limiting the concurrency to prevent this. But we are not cancelling
in progress actions, as the cancellation is shown as a failure in the UI. So even
though some actions will mirror nothing and are unnecessary we will do it so the
UI shows a passing workflow.

## Related
* https://docs.github.com/en/actions/using-jobs/using-concurrency
* https://github.com/DeveloperC286/starlingbanktechnicalchallenge/issues/85